-- ========================================================
-- MIGRATION SCRIPT: DATA LEMBAGA (LAZ, BAZ, FOZ)
-- ========================================================

-- 1. KOSONGKAN TABEL (HATI-HATI JIKA SUDAH ADA DATA)
TRUNCATE TABLE master_lembaga CASCADE;

-- 2. UPDATE CONSTRAINT JENIS LEMBAGA UNTUK MENERIMA 'Asosiasi'
ALTER TABLE master_lembaga DROP CONSTRAINT IF EXISTS master_lembaga_jenis_lembaga_check;
ALTER TABLE master_lembaga ADD CONSTRAINT master_lembaga_jenis_lembaga_check 
CHECK (jenis_lembaga IN ('BAZ', 'LAZ', 'UPZ', 'MPZ', 'NON_OPZ', 'Asosiasi'));

-- 3. INSERT DATA
INSERT INTO master_lembaga (nama_lembaga, jenis_lembaga, tipe_lembaga, is_foz_member)
VALUES 
('NAMA', 'LAZ', 'LAZNAS', true),
('Dompet Dhuafa', 'LAZ', 'LAZNAS', true),
('MAI Foundation', 'LAZ', 'LAZNAS', true),
('Baituzzakah Pertamina', 'LAZ', 'LAZNAS', true),
('Baitul Maal Pupuk Kujang', 'LAZ', 'LAZKAB', true),
('Baitul Maal Muamalat (BMM)', 'LAZ', 'LAZNAS', true),
('BAMUIS BNI', 'LAZ', 'LAZNAS', true),
('MTT Telkomsel', 'LAZ', 'LAZNAS', true),
('Rumah Zakat', 'LAZ', 'LAZNAS', true),
('Inisiatif Zakat Indonesia (IZI)', 'LAZ', 'LAZNAS', true),
('Baitul Maal Hidayatullah (BMH)', 'LAZ', 'LAZNAS', true),
('DT Peduli', 'LAZ', 'LAZNAS', true),
('LAZWAF Al-Azhar', 'LAZ', 'LAZNAS', true),
('LAZNAS LMI', 'LAZ', 'LAZNAS', true),
('LAZNAS YDSF', 'LAZ', 'LAZNAS', true),
('PPPA Daarul Qur''an', 'LAZ', 'LAZNAS', true),
('LAZIS Muhammadiyah (LAZISMU)', 'LAZ', 'LAZNAS', true),
('YBM BRILiaN', 'LAZ', 'LAZNAS', true),
('YBM PLN', 'LAZ', 'LAZNAS', true),
('BSI Maslahat', 'LAZ', 'LAZNAS', true),
('LAZNAS Rumah Yatim Ar-Rohman', 'LAZ', 'LAZNAS', true),
('LAZ Persis', 'LAZ', 'LAZNAS', true),
('Amaliah Astra', 'LAZ', 'LAZNAS', true),
('LAZNAS Dewan Da''wah Islamiyah Indonesia', 'LAZ', 'LAZNAS', true),
('LAZNAS Nurul Hayat', 'LAZ', 'LAZNAS', true),
('LAZIS Jateng', 'LAZ', 'LAZPROV', true),
('Portal Infaq', 'LAZ', 'LAZKAB', true),
('Jakarta Amanah Mulia', 'LAZ', 'LAZKAB', true),
('BANGKIT Foundation', 'LAZ', 'LAZKAB', true),
('NU-Care LAZISNU', 'LAZ', 'LAZNAS', true),
('LAZ Harapan Dhuafa', 'LAZ', 'LAZPROV', true),
('LAZ Dompet Amanah Umat', 'LAZ', 'LAZPROV', true),
('Solo Peduli', 'LAZ', 'LAZPROV', true),
('Baitulmal FKAM', 'LAZ', 'LAZPROV', true),
('ZIS Indosat', 'LAZ', 'LAZNAS', true),
('LAZ DASI NTB', 'LAZ', 'LAZPROV', true),
('Dompet Peduli Lentera Hati (DPLH)', 'LAZ', 'LAZKAB', true),
('DSM Bali', 'LAZ', 'LAZPROV', true),
('Gerak Sedekah Cilacap', 'LAZ', 'LAZKAB', true),
('Indonesia Berbagi', 'LAZ', 'LAZKAB', true),
('LAZ Al Bunyan', 'LAZ', 'LAZPROV', true),
('LAZ AS Salaam Jayapura', 'LAZ', 'LAZPROV', true),
('LAZ Cilacap', 'LAZ', 'LAZKAB', true),
('LAZGIS', 'LAZ', 'LAZPROV', true),
('LAZ Ibnu Sina', 'LAZ', 'LAZKAB', true),
('LAZ Lidzikri', 'LAZ', 'LAZKAB', true),
('LAZ Nurul Fikri', 'LAZ', 'LAZPROV', true),
('LAZ Swadaya Ummah', 'LAZ', 'LAZKAB', true),
('LAZ Ulil Albab', 'LAZ', 'LAZKAB', true),
('LAZ Ummul Quro', 'LAZ', 'LAZPROV', true),
('LAZ YASA Malang', 'LAZ', 'LAZKAB', true),
('LAZ Zakat Sukses', 'LAZ', 'LAZPROV', true),
('LAZIS Nurul Falah', 'LAZ', 'LAZPROV', true),
('LAZIS Syuhada', 'LAZ', 'LAZKAB', true),
('Wahdah Inspirasi Zakat', 'LAZ', 'LAZNAS', true),
('LAZNAS Yatim Mandiri', 'LAZ', 'LAZNAS', true),
('Pondok Sedekah Indonesia', 'LAZ', 'LAZKAB', true),
('Rumah Harapan', 'LAZ', 'LAZPROV', true),
('Rumah Pemberdayaan Ummat', 'LAZ', 'LAZKAB', true),
('Sahabat Dhuafa Mandiri', 'LAZ', 'LAZKAB', true),
('Sahabat Mustahiq Sejahtera', 'LAZ', 'LAZPROV', true),
('Sinergi Foundation', 'LAZ', 'LAZPROV', true),
('Bakrie Amanah', 'LAZ', 'LAZNAS', true),
('Insan Madani Jambi', 'LAZ', 'LAZPROV', true),
('Kotak Amal Indonesia', 'LAZ', 'LAZKAB', true),
('YAKESMA', 'LAZ', 'LAZNAS', true),
('Pulau Harapan Cendekia', 'LAZ', 'LAZKAB', true),
('LAZ YRA', 'LAZ', 'LAZKAB', true),
('Rumah Amal Salman', 'LAZ', 'LAZNAS', true),
('LAZ RYDHA', 'LAZ', 'LAZKAB', true),
('Sedekah Harian', 'LAZ', 'LAZKAB', true),
('Tenda Visi', 'LAZ', 'LAZKAB', true),
('Baitulmal Tazkia', 'LAZ', 'LAZKAB', true),
('LAZ DPU Kaltim', 'LAZ', 'LAZPROV', true),
('LAZ Batam', 'LAZ', 'LAZPROV', true),
('Harapan Amal Mulia', 'LAZ', 'LAZKAB', true),
('LAZIS Sultan Agung', 'LAZ', 'LAZPROV', true),
('Baitul Maal BMT Beringharjo', 'LAZ', 'LAZKAB', true),
('Sahabat Asnaf Indonesia', 'LAZ', 'LAZKAB', true),
('Dompet Al-Qur''an Indonesia', 'LAZ', 'LAZPROV', true),
('Baitul Maal Amanah', 'LAZ', 'LAZKAB', true),
('UPZ UNS', 'LAZ', 'LAZKAB', true),
('MTUA Rekind', 'LAZ', 'LAZKAB', true),
('PAY & DOiT', 'LAZ', 'LAZKAB', true),
('Pelopor Kepedulian', 'LAZ', 'LAZKAB', true),
('Rumah Sosial KUTUB (R-SIK)', 'LAZ', 'LAZKAB', true),
('LAZ Al Irsyad', 'LAZ', 'LAZNAS', true),
('LAZ DKD Magelang', 'LAZ', 'LAZKAB', true),
('Dompet Sejuta Harapan', 'LAZ', 'LAZKAB', true),
('LAZ Ibadurrahman', 'LAZ', 'LAZKAB', true),
('LAZ RIZKI', 'LAZ', 'LAZKAB', true),
('LAZDAI Lampung', 'LAZ', 'LAZKAB', true),
('LAZIS Al Haromain', 'LAZ', 'LAZNAS', true),
('LAZIS Khoiru Ummah', 'LAZ', 'LAZKAB', true),
('Solusi Zakat', 'LAZ', 'LAZKAB', true),
('U Care Indonesia', 'LAZ', 'LAZPROV', true),
('Askar Kauny', 'LAZ', 'LAZKAB', true),
('Baitul Qur''an Indonesia', 'LAZ', 'LAZKAB', true),
('DOMYADHU', 'LAZ', 'LAZNAS', true),
('LAZISNUR', 'LAZ', 'LAZKAB', true),
('Yuk Peduli', 'LAZ', 'LAZKAB', true),
('Infaq Berkah', 'LAZ', 'LAZKAB', true),
('STF UIN Syarif Hidayatullah', 'LAZ', 'LAZPROV', true),
('LAZ Darussalam', 'LAZ', 'LAZNAS', true),
('LAZNAS ENERGI KEBAIKAN ROKAN', 'LAZ', 'LAZPROV', true),
('Graha Yatim & Dhuafa', 'LAZ', 'LAZPROV', true),
('LAZ Al Kahfi Peduli', 'LAZ', 'LAZKAB', true),
('Taman Zakat Indonesia', 'LAZ', 'LAZPROV', true),
('Itqan Peduli', 'LAZ', 'LAZKAB', true),
('LAZNAS Mizan Amanah', 'LAZ', 'LAZNAS', true),
('Goedang Zakat Al- Khairaat', 'LAZ', 'LAZKAB', true),
('Panti Yatim & Zakat', 'LAZ', 'LAZNAS', true),
('BaitulMaalKu', 'LAZ', 'LAZPROV', true),
('Dompet Peduli Ummat Jatim', 'LAZ', 'LAZKAB', true),
('UPZ BAZNAS Semen Padang', 'LAZ', 'LAZPROV', true),
('Huda Cendekia', 'LAZ', 'LAZKAB', true),
('Amanah Takaful', 'LAZ', 'LAZKAB', true),
('LAZIS Al Hilal', 'LAZ', 'LAZPROV', true),
('LAZIS Qur''an', 'LAZ', 'LAZKAB', true),
('Suara Hati Sidoarjo', 'LAZ', 'LAZKAB', true),
('Amal Terbaik Madania', 'LAZ', 'LAZKAB', true),
('ZISWAF At - Taufiq', 'LAZ', 'LAZKAB', true),
('OK OCE Peduli', 'LAZ', 'LAZKAB', true),
('LAZ As-Salam Timika', 'LAZ', 'LAZKAB', true),
('Sukoharjo Peduli', 'LAZ', 'LAZKAB', true),
('LAZ AZKA Al Baitul Amien Jember', 'LAZ', 'LAZKAB', true),
('Baitulmaal Munzalan Indonesia', 'LAZ', 'LAZNAS', true),
('Al-Qoyyim Sukoharjo', 'LAZ', 'LAZKAB', true),
('Berdaya Foundation', 'LAZ', 'LAZKAB', true),
('LAZ DAPA', 'LAZ', 'LAZKAB', true),
('Yayasan Hadji Kalla', 'LAZ', 'LAZNAS', true),
('LAZ Musa''adatul Ummah', 'LAZ', 'LAZKAB', true),
('LAZIS UNISIA', 'LAZ', 'LAZPROV', true),
('LAZ BMBU Kota Bontang', 'LAZ', 'LAZKAB', true),
('LAZ Rumah Peduli Umat', 'LAZ', 'LAZKAB', true),
('LAZ Sahabat Kebaikan Umat (SAKU)', 'LAZ', 'LAZKAB', true),
('Insan Peduli Umat (IPU)', 'LAZ', 'LAZPROV', true),
('Yayasan Gugus Karya Mandiri', 'LAZ', 'LAZKAB', true),
('Baitul Maal Merapi Merbabu (BM3)', 'LAZ', 'LAZPROV', true),
('Sahabat Yatim Indonesia', 'LAZ', 'LAZNAS', true),
('LAZ Madani Human Care (MHC) Dumai', 'LAZ', 'LAZKAB', true),
('LAZ Persada Jatim Indonesia', 'LAZ', 'LAZPROV', true),
('LAZIS Baiturrahman', 'LAZ', 'LAZKAB', true),
('Nusa Charity', 'LAZ', 'LAZKAB', true),
('ZIS Yayasan Annur Insan Pembangkitan (YANIP)', 'LAZ', 'LAZNAS', true),
('Darul Akrim Inayah', 'LAZ', 'LAZKAB', true),
('LAZ Masjid Raya Bintaro (LAZ MRBJ)', 'LAZ', 'LAZKAB', true),
('LAZ Zakatku Bakti Persada', 'LAZ', 'LAZKAB', true),
('Yayasan Rute Langkah Amanah', 'LAZ', 'LAZKAB', true),
('LAZ Risalah Charity', 'LAZ', 'LAZKAB', true),
('LAZ Tamasa', 'LAZ', 'LAZPROV', true),
('LAZ BKB', 'LAZ', 'LAZPROV', true),
('T.CARE', 'LAZ', 'LAZKAB', true),
('Baitul Maal Al Furqon', 'LAZ', 'LAZKAB', true),
('Explore! Humanity', 'LAZ', 'LAZKAB', true),
('Laju Peduli', 'LAZ', 'LAZKAB', true),
('LAZ Balqis Peduli', 'LAZ', 'LAZKAB', true),
('LAZ MKU', 'LAZ', 'LAZNAS', true),
('Cahaya Islam Mutiara Imani', 'LAZ', 'LAZKAB', true),
('LAZ ZISWAF Masjid Pelajar', 'LAZ', 'LAZPROV', true),
('Saku Yatim', 'LAZ', 'LAZKAB', true),
('LAZ OPSEZI', 'LAZ', 'LAZPROV', true),
('Inovasi Zakat Indonesia', 'LAZ', 'LAZKAB', true),
('Nusantara Palestina Center', 'LAZ', 'LAZNAS', true),
('LAZ Kesejahteraan Umat', 'LAZ', 'LAZKAB', true),
('ROJA Peduli', 'LAZ', 'LAZKAB', true),
('Indonesia Berbagi Peduli', 'LAZ', 'LAZKAB', true),
('LAZ Al-Aqsha De Latinos', 'LAZ', 'LAZKAB', true),
('Percikan Iman', 'LAZ', 'LAZPROV', true),
('Pusat Amal Kebajikan', 'LAZ', 'LAZKAB', true),
('LAZNAS AQL', 'LAZ', 'LAZNAS', true),
('LAZ Assyifa Peduli', 'LAZ', 'LAZKAB', true),
('LAZ Generasi Rabbani', 'LAZ', 'LAZKAB', true),
('LAZ Abulyatama Indonesia', 'LAZ', 'LAZNAS', true),
('Indonesia Beramal Sholeh (IBS)', 'LAZ', 'LAZPROV', true),
('MIM Foundation', 'LAZ', 'LAZKAB', true),
('Asar Humanity', 'LAZ', 'LAZNAS', true),
('Griya Zakat', 'LAZ', 'LAZKAB', true),
('Griya Yatim dan Dhuafa (GYD)', 'LAZ', 'LAZNAS', true),
('LAZ Al-Bahjah', 'LAZ', 'LAZKAB', true),
('LAZ ASHPEN', 'LAZ', 'LAZKAB', true),
('LAZ Sahabat Almira Indonesia', 'LAZ', 'LAZKAB', true),
('LAZ Salam Setara', 'LAZ', 'LAZNAS', true),
('LAZIS Sabilillah', 'LAZ', 'LAZKAB', true),
('LAZ Pundi Surga', 'LAZ', 'LAZKAB', true),
('LAZ DARUL HIKAM', 'LAZ', 'LAZPROV', true),
('ALZIS Alwashliyah', 'LAZ', 'LAZNAS', true),
('LAZNAS MPAQ', 'LAZ', 'LAZNAS', true),
('LAZIS Agnia Care', 'LAZ', 'LAZNAS', true),
('LAZ Hidayah Berbagi Indonesia', 'LAZ', 'LAZKAB', true),
('LAZ Nur Hidayah', 'LAZ', 'LAZKAB', true),
('Lazis Cahaya Peduli', 'LAZ', 'LAZKAB', true),
('LAZ SEMBADA', 'LAZ', 'LAZKAB', true),
('LAZ Islamic Relief Indonesia', 'LAZ', 'LAZNAS', true),
('Baitul Maal Timoho Sejahtera', 'LAZ', 'LAZKAB', true),
('LAZ SYAMSUL ULUM', 'LAZ', 'LAZPROV', true),
('LAZ BM AL-ITQON', 'LAZ', 'LAZKAB', true),
('LAZ Swara Mandiri Ummat', 'LAZ', 'LAZKAB', true),
('Lembaga Amil Zakat Pekanbaru Berdaya', 'LAZ', 'LAZKAB', false),
('Bakti Peduli Indonesia', 'LAZ', 'LAZKAB', false),
('IKATAN DA''I INDONESIA', 'LAZ', 'LAZNAS', false),
('LAZ ZAKATEL CITRA CARAKA', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN SOLIDARITAS INSAN PEDULI', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN MANSYAUL FADLLI', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN AS''ADIYAH PUSAT SENGKANG', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN AS-SALAM MALUKU', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN LUMBUNG ZAKAT', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN NURUL FALAH YOGYAKARTA', 'LAZ', 'LAZKAB', false),
('LAZ PERKUMPULAN SYARIKAT ISLAM', 'LAZ', 'LAZNAS', false),
('Lembaga Amil Zakat Infaq dan Sedekah Utsmaniyah Nusantara (LAZISMA NUSANTARA)', 'LAZ', 'LAZPROV', false),
('LAZ Imam Bukhari (LAZIB)', 'LAZ', 'LAZKAB', false),
('LAZNAS HALAQOH SILSILAH ILMIYAH BERBAGI (HSI BERBAGI)', 'LAZ', 'LAZNAS', false),
('LAZ YAYASAN WARGA MUSLIM GRAHA RAYA', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN DOMPET YATIM DAN MESJID', 'LAZ', 'LAZKAB', false),
('LAZ BAITUL MAAL BARAKATUL UMMAH', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN DARUNNAJAH SEJAHTERA MANDIRI', 'LAZ', 'LAZNAS', false),
('LAZ YURBI SHADAQAT', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN AL AMIEN PRENDUAN', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN ATTAQWA', 'LAZ', 'LAZPROV', false),
('LAZ YAYASAN ADZKIA', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN DARUL FATTAH PEDULI', 'LAZ', 'LAZKAB', false),
('Yayasan Aisyah Binti Abu Bakar Li al-Dakwah', 'LAZ', 'LAZKAB', false),
('Yayasan Kita Peduli Kemanusiaan', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN AL MUTHI''IN', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN MEJLIS PENGAJIAN ISLAM SURAKARTA', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN PEMBERDAYAAN INSAN MULIA ASY SYAMIL', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN ALBI MENEBAR MANFAAT', 'LAZ', 'LAZKAB', false),
('yayasan aksa mahmud / bosowa peduli', 'LAZ', 'LAZPROV', false),
('LAZ YAYASAN RINTISAN AMAL BUNDA', 'LAZ', 'LAZKAB', false),
('Amal Sholeh Sejahtera', 'LAZ', 'LAZPROV', false),
('Yayasan Indonesia Kuat Bermartabat', 'LAZ', 'LAZNAS', false),
('YAYASAN AMAL KAMPUNG MAGHFIRAH', 'LAZ', 'LAZKAB', false),
('YAYASAN INISIATIF IHSANI MAHASIN', 'LAZ', 'LAZKAB', false),
('Yayasan Nadwah Islamiah', 'LAZ', 'LAZKAB', false),
('Yayasan Amal Saya Peduli', 'LAZ', 'LAZNAS', false),
('YAYASAN INVESTA CENDEKIA AMANAH DEPOK', 'LAZ', 'LAZPROV', false),
('YAYASAN TASDIQUL QUR''AN', 'LAZ', 'LAZKAB', false),
('YAYASAN RUMAH YATIM DAN DHUAFA HIFZHUL AMANAH', 'LAZ', 'LAZKAB', false),
('LAZ Dompet Sosial Al-Fityan', 'LAZ', 'LAZNAS', false),
('LAZ Alumni FK Unand', 'LAZ', 'LAZKAB', false),
('LAZ KESEJAHTERAAN UKHUWWAH', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN TAZAKKA', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN ZAKAT KITA BERSAMA', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN SOSIAL AL IRSYAD CILACAP', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN DANA SOSIAL NURUL ISLAM AMANAH BATAM', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN DANA KEMANUSIAAN DHUAFA', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN BANGUN NEGERI KITA', 'LAZ', 'LAZKAB', false),
('LAZ USWAH HASANAH PERWIRA', 'LAZ', 'LAZKAB', false),
('LAZ UMMAT SEJAHTERA', 'LAZ', 'LAZKAB', false),
('LAZ SENYUM DHUAFA', 'LAZ', 'LAZKAB', false),
('LAZ MUSLIM PEDULI', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN MUHAJIR PEDULI INDONESIA', 'LAZ', 'LAZKAB', false),
('LAZ GRAHA DHUAFA INDONESIA', 'LAZ', 'LAZKAB', false),
('LAZ CENDEKIA MALUKU', 'LAZ', 'LAZPROV', false),
('LAZ AMAL MADANI INDONESIA', 'LAZ', 'LAZKAB', false),
('LAZ AL MAUNAH SUNNIYAH SALAFIYAH PASURUAN', 'LAZ', 'LAZPROV', false),
('LAZ AGEN SEDEKAH KULONPROGO', 'LAZ', 'LAZKAB', false),
('LAZ  WAQAF INFAQ ZAKAT DAN SODAQOH PESANTREN', 'LAZ', 'LAZNAS', false),
('LAZ PERKUMPULAN KELUARGA BESAR PELAJAR ISLAM INDONESIA', 'LAZ', 'LAZNAS', false),
('LAZ FITHRAH INSANI CARE', 'LAZ', 'LAZPROV', false),
('LAZIS YAYASAN SAHABAT MUADZ INDONESIA', 'LAZ', 'LAZPROV', false),
('LAZIS YAYASAN BADAN WAKAF UNIVERSITAS ISLAM INDONESIA', 'LAZ', 'LAZKAB', false),
('LAZ YAYASAN SEMAI SINERGI UMAT', 'LAZ', 'LAZPROV', false),
('LAZ YAYASAN RUANG AMAL INDONESIA', 'LAZ', 'LAZNAS', false),
('LAZ YAYASAN CT ARSA', 'LAZ', 'LAZNAS', false),
('LAZ YAYASAN ASSALAM FIL ALAMIN', 'LAZ', 'LAZNAS', false),
('LAZ TELAGA BIJAK EL ZAWA', 'LAZ', 'LAZNAS', false),
('LAZ SIDOGIRI', 'LAZ', 'LAZNAS', false),
('LAZ PEDULI DAKWAH', 'LAZ', 'LAZPROV', false),
('LAZ Djalaluddin Pane Foundation (DPF)', 'LAZ', 'LAZNAS', false),
('LAZ Ar Raudhah Ihsan Foundation', 'LAZ', 'LAZKAB', false),
('LAZ Dewan Masjid Indonesia (DMI)', 'LAZ', 'LAZNAS', false),
('LAZ Yayasan Asrama Pelajar Islam (YAPI)', 'LAZ', 'LAZKAB', false),
('LAZ Ummul Quro'' Bogor', 'LAZ', 'LAZKAB', false),
('LAZ RABBANI', 'LAZ', 'LAZKAB', false),
('LAZ Al Kasyaf Bakti Mulya', 'LAZ', 'LAZKAB', false),
('LAZ Insan Masyarakat Madani', 'LAZ', 'LAZKAB', false),
('LAZ Yayasan Nashirussunnah Permata (Yashiruna)', 'LAZ', 'LAZKAB', false),
('LAZ Sakinah Berkah Mandiri', 'LAZ', 'LAZKAB', false),
('LAZ Bakti Achmad Zaky', 'LAZ', 'LAZKAB', false),
('LAZ Gelora Insan Mandiri', 'LAZ', 'LAZKAB', false),
('LAZ Baitul Misbah', 'LAZ', 'LAZKAB', false),
('LAZ Jabalnur Pesantenan Pati', 'LAZ', 'LAZKAB', false),
('LAZ Fadhli Rabbi', 'LAZ', 'LAZKAB', false),
('LAZ Excellent Zakat', 'LAZ', 'LAZKAB', false),
('LAZ Mukmin Mandiri', 'LAZ', 'LAZPROV', false),
('LAZ LAGZIS Peduli', 'LAZ', 'LAZNAS', false),
('LAZ Majlis Amal Sholeh', 'LAZ', 'LAZKAB', false),
('LAZ Al-Madina Surabaya', 'LAZ', 'LAZKAB', false),
('LAZ Kreasi Bangun Semesta', 'LAZ', 'LAZPROV', false),
('LAZ Sinergi Membangun Ummat', 'LAZ', 'LAZKAB', false),
('LAZ As''adiyah Wonomulyo', 'LAZ', 'LAZPROV', false),
('Baitul Mal Prov. Aceh', 'BAZ', 'BAZNAS_PROV', false),
('Baitul Mal Kab. Aceh Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Aceh Tenggara', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Aceh Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Aceh Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Aceh Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Aceh Besar', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Pidie', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Aceh Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Simeulue', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Aceh Singkil', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Bireuen', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Aceh Barat Daya', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Gayo Lues', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Aceh Jaya', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Nagan Raya', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Aceh Tamiang', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Bener Meriah', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kab. Pidie Jaya', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kota Banda Aceh', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kota Sabang', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kota Lhokseumawe', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kota Langsa', 'BAZ', 'BAZNAS_KABKOTA', false),
('Baitul Mal Kota Subulussalam', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Sumatera Utara', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Tapanuli Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tapanuli Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tapanuli Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Nias', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Langkat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Karo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Deli Serdang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Simalungun', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Asahan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Labuhan Batu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Dairi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Toba Samosir', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mandailing Natal', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Nias Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pak Pak Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Humbang Hasundutan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Samosir', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Serdang Bedagai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Batubara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Padang Lawas Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Padang Lawas', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Labuhan Batu Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Labuhan Batu Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Nias Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Nias Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Medan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Pematang Siantar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Sibolga', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Tanjung Balai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Binjai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Tebing Tinggi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Padang Sidempuan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Gunung Sitoli', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Sumatera Barat', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Pesisir Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Solok', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sijunjung', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tanah Datar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Padang Pariaman', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Agam', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lima Puluh Kota', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pasaman', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kep. Mentawai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Dharmasraya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Solok Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pasaman Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Padang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Solok', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Sawahlunto', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Padang Panjang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Bukittinggi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Payakumbuh', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Pariaman', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Riau', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Kampar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Indragiri Hulu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bengkalis', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Indragiri Hilir', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pelalawan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Rokan Hulu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Rokan Hilir', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Siak', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kuantan Singingi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kepulauan Meranti', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Pekanbaru', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Dumai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Jambi', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Kerinci', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Merangin', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sarolangun', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Batanghari', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Muaro Jambi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tanjung Jabung Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tanjung Jabung Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bungo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tebo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Jambi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Sungai Penuh', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Sumatera Selatan', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Ogan Komering Ulu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Ogan Komering Ilir', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Muara Enim', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lahat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Musi Rawas', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Musi Banyuasin', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Banyuasin', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Ogan Komering Ulu Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Ogan Komering Ulu Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Ogan Ilir', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Empat Lawang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Penukal Abab Lematang Ilir', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Musi Rawas Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Palembang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Pagar Alam', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Lubuk Linggau', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Prabumulih', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Bengkulu', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Bengkulu Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Rejang Lebong', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bengkulu Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kaur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Seluma', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mukomuko', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lebong', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kepahiang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bengkulu Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Bengkulu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Lampung', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Lampung Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lampung Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lampung Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lampung Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tulang Bawang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tanggamus', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lampung Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Way Kanan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pesawaran', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pringsewu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mesuji', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tulang Bawang Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pesisir Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Bandar Lampung', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Metro', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Kep. Bangka Belitung', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Bangka', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Belitung', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bangka Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bangka Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bangka Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Belitung Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Pangkal Pinang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Kep. Riau', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Bintan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Karimun', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Natuna', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lingga', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kep. Anambas', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Batam', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Tanjung Pinang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. DKI Jakarta', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Kepulauan Seribu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Jakarta Pusat', 'BAZ', 'BAZNAS_PUSAT', false),
('LAZ Baitul Maal BRILiaN', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Jakarta Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Jakarta Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Jakarta Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('LAZ Baitul Maal Hidayatullah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS (Pusat)', 'BAZ', 'BAZNAS_PUSAT', false),
('BAZNAS Kota Jakarta Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('LAZ Baitulmaal Muamalat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Jawa Barat', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Bogor', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Cianjur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sukabumi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bandung', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Garut', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tasikmalaya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Ciamis', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kuningan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Cirebon', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Majalengka', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sumedang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Indramayu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Subang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Purwakarta', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Karawang', 'BAZ', 'BAZNAS_KABKOTA', false),
('LAZ Baitulmaalku', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bekasi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bandung Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pangandaran', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Bogor', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Sukabumi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Bandung', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Cirebon', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Bekasi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Depok', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Cimahi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Tasikmalaya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Banjar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Jawa Tengah', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Cilacap', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Banyumas', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Purbalingga', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Banjarnegara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kebumen', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Purworejo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Wonosobo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Magelang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Boyolali', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Klaten', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sukoharjo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Wonogiri', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Karanganyar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sragen', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Grobogan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Blora', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Rembang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pati', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kudus', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Jepara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Demak', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Semarang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Temanggung', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kendal', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Batang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pekalongan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pemalang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tegal', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Brebes', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Magelang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Surakarta', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Salatiga', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Semarang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Pekalongan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Tegal', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. DI Yogyakarta', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Kulon Progo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bantul', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Gunung Kidul', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sleman', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Yogyakarta', 'BAZ', 'BAZNAS_KABKOTA', false),
('LAZ Baitul Maal Merapi Merbabu', 'BAZ', 'BAZNAS_KABKOTA', false),
('LAZ Baitul Maal Timoho', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Jawa Timur', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Pacitan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Ponorogo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Trenggalek', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tulungagung', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Blitar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kediri', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Malang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lumajang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Jember', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Banyuwangi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bondowoso', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Situbondo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Probolinggo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pasuruan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sidoarjo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mojokerto', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Jombang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Nganjuk', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Madiun', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Magetan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Ngawi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bojonegoro', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tuban', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lamongan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Gresik', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bangkalan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sampang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pamekasan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sumenep', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Kediri', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Blitar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Malang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Probolinggo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Pasuruan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Mojokerto', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Madiun', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Surabaya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Batu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Banten', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Pandeglang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lebak', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tangerang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Serang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Tangerang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Cilegon', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Serang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Tangerang Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Bali', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Jembrana', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tabanan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Badung', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Gianyar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Klungkung', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bangli', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Karangasem', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Buleleng', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Denpasar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Nusa Tenggara Barat', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Lombok Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lombok Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lombok Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sumbawa', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Dompu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bima', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sumbawa Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lombok Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Mataram', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Bima', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Nusa Tenggara Timur', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Kupang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Timor Tengah Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Timor Tengah Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Belu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Alor', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Flores Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sikka', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Ende', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Ngada', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Manggarai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sumba Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sumba Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lembata', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Rote Ndao', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Manggarai Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Nagekeo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sumba Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sumba Barat Daya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Manggarai Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sabu Raijua', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Malaka', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Kupang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Kalimantan Barat', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Sambas', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mempawah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sanggau', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Ketapang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sintang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kapuas Hulu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bengkayang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Landak', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sekadau', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Melawi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kayong Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kubu Raya', 'BAZ', 'BAZNAS_KABKOTA', false),
('LAZ Baitulmaal Munzalan Indonesia', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Pontianak', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Singkawang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Kalimantan Tengah', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Kotawaringin Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kotawaringin Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kapuas', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Barito Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Barito Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Katingan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Seruyan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sukamara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lamandau', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Gunung Mas', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pulang Pisau', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Murung Raya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Barito Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Palangkaraya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Kalimantan Selatan', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Tanah Laut', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kotabaru', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Banjar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Barito Kuala', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tapin', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Hulu Sungai Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Hulu Sungai Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Hulu Sungai Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tabalong', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tanah Bumbu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Balangan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Banjarmasin', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Banjarbaru', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Kalimantan Timur', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Paser', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kutai Kartanegara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Berau', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kutai Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kutai Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Penajam Paser Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mahakam Ulu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Balikpapan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Samarinda', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Bontang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Kalimantan Utara', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Bulungan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Malinau', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Nunukan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tana Tidung', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Tarakan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Sulawesi Utara', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Bolaang Mongondow', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Minahasa', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kep. Sangihe', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kepulauan Talaud', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Minahasa Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Minahasa Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Minahasa Tenggara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bolaang Mongondow Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kep. Siau Tagulandang Biaro', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bolaang Mongondow Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bolaang Mongondow Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Manado', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Tomohon', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Bitung', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Kotamobagu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Sulawesi Tengah', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Banggai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Poso', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Donggala', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Toli-Toli', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Buol', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Morowali', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Banggai Kepulauan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Parigi Moutong', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tojo Una Una', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sigi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Banggai Laut', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Morowali Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Palu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Sulawesi Selatan', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Kep. Selayar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bulukumba', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bantaeng', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Jeneponto', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Takalar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Gowa', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sinjai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bone', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Maros', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pangkajene Kepulauan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Barru', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Soppeng', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Wajo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sidenreng Rappang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pinrang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Enrekang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Luwu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tana Toraja', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Luwu Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Luwu Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Toraja Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Makassar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Parepare', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Palopo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Sulawesi Tenggara', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Kolaka', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Konawe', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Muna', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Buton', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Konawe Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bombana', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Wakatobi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kolaka Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Konawe Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Buton Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kolaka Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Konawe Kepulauan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Muna Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Buton Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Buton Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Kendari', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Baubau', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Gorontalo', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Gorontalo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Boalemo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Bone Bolango', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pohuwato', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Gorontalo Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Gorontalo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Sulawesi Barat', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Pasangkayu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mamuju', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mamasa', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Polewali Mandar', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Majene', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mamuju Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Maluku', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Maluku Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Maluku Tenggara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Maluku Tenggara Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Buru', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Seram Bagian Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Seram Bagian Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kepulauan Aru', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Maluku Barat Daya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Buru Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Ambon', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Tual', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Maluku Utara', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Halmahera Barat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Halmahera Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Halmahera Utara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Halmahera Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kep. Sula', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Halmahera Timur', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pulau Morotai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Taliabu', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Ternate', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Tidore Kepulauan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Papua', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Merauke', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Jayawijaya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Jayapura', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Nabire', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kepulauan Yapen', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Biak Numfor', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Puncak Jaya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Paniai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mimika', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sarmi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Keerom', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pegunungan Bintang', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Yahukimo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tolikara', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Waropen', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Boven Digoel', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mappi', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Asmat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Supiori', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mamberamo Raya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Mamberamo Tengah', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Yalimo', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Lanny Jaya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Nduga', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Puncak', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Dogiyai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Intan Jaya', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Deiyai', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Jayapura', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Prov. Papua Barat', 'BAZ', 'BAZNAS_PROV', false),
('BAZNAS Kab. Sorong', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Manokwari', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Fak Fak', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Sorong Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Raja Ampat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Teluk Bintuni', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Teluk Wondama', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Kaimana', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Tambrauw', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Maybrat', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Manokwari Selatan', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kab. Pegunungan Arfak', 'BAZ', 'BAZNAS_KABKOTA', false),
('BAZNAS Kota Sorong', 'BAZ', 'BAZNAS_KABKOTA', false),
('Forum Zakat', 'Asosiasi', 'LAZNAS', true);